# Copyright (c) 2018-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2018-present Sven Greb <code@svengreb.de>

# Project:    Styleguide Markdown
# Repository: https://github.com/arcticicestudio/styleguide-markdown
# License:    MIT
# References:
#   https://circleci.com/docs/2.0
#   https://circleci.com/docs/2.0/circleci-images/#nodejs

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess-npm-install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build-docs
          command: npm run docs:build
      - store_artifacts:
          path: build/docs
